spring:
  application:
    name: BookingClone
  datasource:
    url: jdbc:postgresql://localhost:5434/bookingCloneDb
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 7070
  servlet:
    context-path: /api/v1

jwt:
  secretKey: fpbergipervit4340g80rb8ehbh304ghsdlkverognebbns

frontend:
  url: http://localhost:7070

stripe:
  webhook:
    secret: whsec_3456f052e7e0eb29caf088e905a282543df3bd8563a4ad689553dc3a635cd2b9
  secret:
    key: sk_test_51SoLglCHnm6iDOHg5cs3fhqoIoBws0KkFBqycOnq8lCd1RJW54iSLDvmgERXG9IYILiVfYWuOnmdS2BBr3AYwk5X00tPoqNeb3